LIB = libland.a
SRCDIR = src
SUBDIRS = allegro allegrogl

GUARD_PREFIX = LAND_LAND_

ADDLIB = -lagl -lGL -lGLU

DEBUGMODE = 1

PRETTY = 1
ADDFLAG = -DLAND_USE_OPENGL

USECPROTO = 1

include ../makefile.template

install:
	cp libland.a /usr/local/lib
	for i in "" "/allegro" "/allegrogl"; do \
		mkdir -p /usr/local/include/land$$i; \
		cp pro$$i/*.{h,pro} /usr/local/include/land$$i; \
	done

uninstall:
	-rm /usr/local/lib/libland.a
	-rm -r /usr/local/include/land
