# vi: syntax=python
import glob, os

try: os.mkdir("scons")
except OSError: pass

examples = [ex for ex in glob.glob("*") if os.path.isdir(ex) and ex != "scons"]

for ex in examples:
    srcdir = os.path.join(ex, "src")
    cdir = os.path.join(ex, "c")

    cfiles = []
    pyfiles = glob.glob(os.path.join(srcdir, "*.py"))

    env = Environment(ENV = {'PATH' : os.environ['PATH']})

    BUILDDIR = os.path.join("scons", "build")

    for py in pyfiles:
        h = cdir + "/" + py[len(srcdir) + 1:-3] + ".h"
        c = cdir + "/" + py[len(srcdir) + 1:-3] + ".c"
        name = py[len(srcdir) + 1:-3]
        com = "scramble.py -i %s -c %s -h %s -n %s" % (py, c, h, name)
        env.BuildDir(cdir, srcdir)
        env.Command([c, h], py, com)
        cfiles += [c]

    env.Append(CPPPATH = ["../include/land"])
    env.Append(LIBPATH = ["../lib/posix"])

    if ARGUMENTS.get("debug", 0):
        env.Append(CCFLAGS = "-g -DLAND_MEMLOG")
        env.Append(LIBS = ["landd", "agld", "fudgefontd"])
        env.ParseConfig("allegro-config --shared debug")
        BUILDDIR = os.path.join(BUILDDIR, "debug")
    else:
        env.Append(LIBS = ["land", "agl", "fudgefont"])
        env.ParseConfig("allegro-config --shared release")
        BUILDDIR = os.path.join(BUILDDIR, "release")

    BUILDDIR = os.path.join(BUILDDIR, ex)

    env.Append(CCFLAGS = "--std=gnu99")
    env.Append(LIBS = ["ldpng", "png",
        "freetype", "GL", "GLU", "dumb", "jpgal"])
    env.Append(LIBS = ["logg", "ogg", "vorbis", "vorbisfile"])

    env.SConsignFile("scons/signatures")

    env.BuildDir(BUILDDIR, cdir)
    sources = [os.path.join(BUILDDIR, os.path.split(x)[1]) for x in cfiles]
    prog = env.Program(os.path.join(ex, ex), sources)
    env.Default([srcdir, prog])

