EXE = draw

SRCDIR = src
ADDFLAG = -I../../pro

PRETTY = 1

USECPROTO = 1

DEBUGMODE = 1
STATICLINK = 1

ALLEGROGL = 1

ADDLIB = -L../.. -lland -lldpng -lpng -lglyphkeeper-agl -lfreetype

include ../makefile.template
